name: Run Cargo Tests

on:
  push:
    branches:
      - main
    # Do not run, unless code related paths change
    paths:
      - 'src/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
      - '.github/workflows/*.yml'

# Kill actions when new ones start
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# On all platforms, run tests in both debug and release mode!
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Run cargo test in debug mode
        run: cargo test --verbose

      - name: Run cargo test in release mode
        run: cargo test --verbose --release
